</$objtype/mkfile

LIB=/$objtype/lib/libwidget.a

OFILES=\
	base.$O		\
	textbox.$O	\
	button.$O	\
	box.$O

HDR=widget.h

HCOMP=\
	base.h		\
	textbox.h	\
	box.h		\
	button.h

HFILES=\
	/sys/include/$HDR	\
	w-internal.h

MANPAGES=\
	/sys/man/2/widget

</sys/src/cmd/mksyslib

install:V: $MANPAGES

/sys/include/$HDR: $HCOMP
	cat $prereq >$target

# TODO generalize
/sys/man/2/widget: widget.2.man
	cp $prereq $target
